[2024-06-15T14:16:05.073+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.produce_usage manual__2024-06-15T14:15:41.604085+00:00 [queued]>
[2024-06-15T14:16:05.088+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.produce_usage manual__2024-06-15T14:15:41.604085+00:00 [queued]>
[2024-06-15T14:16:05.089+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-15T14:16:05.102+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): produce_usage> on 2024-06-15 14:15:41.604085+00:00
[2024-06-15T14:16:05.110+0000] {standard_task_runner.py:57} INFO - Started process 169 to run task
[2024-06-15T14:16:05.112+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'produce_usage', 'manual__2024-06-15T14:15:41.604085+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpgr7ugp4q']
[2024-06-15T14:16:05.115+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask produce_usage
[2024-06-15T14:16:05.153+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.produce_usage manual__2024-06-15T14:15:41.604085+00:00 [running]> on host 474613fe749c
[2024-06-15T14:16:05.216+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='produce_usage' AIRFLOW_CTX_EXECUTION_DATE='2024-06-15T14:15:41.604085+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-15T14:15:41.604085+00:00'
[2024-06-15T14:16:05.218+0000] {logging_mixin.py:151} INFO - combine data creating folder /opt/*** datalake/usage/animeAnalysis/AnimeTop300/20240615
[2024-06-15T14:16:05.349+0000] {logging_mixin.py:151} INFO - An error occurred: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-06-15T14:16:05.350+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/lib/combine_data.py", line 86, in main
    combine_data(current_day)
  File "/opt/airflow/dags/lib/combine_data.py", line 21, in combine_data
    spark = SparkSession.builder.appName("CombineData").getOrCreate()
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-06-15T14:16:05.360+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=main_dag, task_id=produce_usage, execution_date=20240615T141541, start_date=20240615T141605, end_date=20240615T141605
[2024-06-15T14:16:05.371+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task produce_usage ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 169)
[2024-06-15T14:16:05.405+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-15T14:16:05.426+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
